name: .NET nuget released

on:
  release:
    types: 
      - released

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: package
      run: dotnet pack -c Release
    - name: push
      env: 
        nugetkey: ${{ secrets.nugetkey }}
      run: for x in  $(find . -name "*.nupkg" -print); do dotnet nuget push -k $nugetkey $x; done
